services:
  elasticsearch:
    image: elasticsearch:8.11.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - elastic-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  kibana:
    image: kibana:8.11.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - SERVER_NAME=kibana
      - SERVER_HOST=0.0.0.0
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - elastic-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5601/api/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Development FastAPI app container (with source code volumes)
  fastapi-dev:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: fastapi-dev
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - KIBANA_HOST=kibana
      - KIBANA_PORT=5601
      - ENVIRONMENT=development
      - LOG_LEVEL=DEBUG
      - DEBUG=true
    ports:
      - "8000:8000"
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - elastic-network
    volumes:
      - ./app:/app/app:ro  # Mount source code as read-only
      - ./config:/app/config:ro  # Mount config as read-only
      - ./tests:/app/tests:ro  # Mount tests as read-only
      - ./pyproject.toml:/app/pyproject.toml:ro
      - ./uv.lock:/app/uv.lock:ro
      - ./.env:/app/.env:ro
      - ./logs:/app/logs  # Logs directory (read-write)
    restart: unless-stopped
    profiles:
      - dev  # Start with --profile dev
    command: ["uv", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  # Optional: FastAPI app container (for production deployment)
  fastapi-app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: fastapi-app
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - KIBANA_HOST=kibana
      - KIBANA_PORT=5601
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
    ports:
      - "8001:8000"  # Use different port to avoid conflict with dev
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy
    networks:
      - elastic-network
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    profiles:
      - production  # Only start with --profile production

volumes:
  elasticsearch_data:
    driver: local

networks:
  elastic-network:
    driver: bridge